### PR TITLE
maybe deployments? like this?

### PR DESCRIPTION
**Pull request by archieco**
Scoping the problem the way I did about teams and other labels would
make more sense with a story around deployments. So I made these
changes. Expecting that we would slim this down further if that's the
path to take.

### CODE REVIEW

**Comment by maliksalman** [comment]
Did you intend to keep the appV1Api call as synchronous vs the coreV1Api call as asynchronous? OR we are just going to turn this into a Deployments example rather than a Pods example

**Comment by maliksalman** [comment]
Another observation is that the way we are creating the deployments and labeling them in the shell script, the `teams` label doesn't propagate to the pods. This is because the team label is on the deployment's .metadata.labels itself and not in the .spec.template.metadata.labels - which would get propagated. 

We can just completely forget about talking about the V1Pod API and only concentrate on the V1Deployment API. Alternatively, we can just start pods directly using `kubectl run POD_NAME --image=blabla` in our shell script

**Comment by archieco** [comment]
> Another observation is that the way we are creating the deployments and labeling them in the shell script, the `teams` label doesn't propagate to the pods. This is because the team label is on the deployment's .metadata.labels itself and not in the .spec.template.metadata.labels - which would get propagated.
> 

I was only trying to keep that within the scope of what I could do with that label command since it's not really the practice I would recommend but going deeper into templates reduces the focus of the article. Maybe we could make a callout about that and link to a future article about our recommendations for templates? 


> We can just completely forget about talking about the V1Pod API and only concentrate on the V1Deployment API. Alternatively, we can just start pods directly using `kubectl run POD_NAME --image=blabla` in our shell script

If you're ok with the change in direction I would go for just deployments on this pass.

**Comment by archieco** [comment]
> Did you intend to keep the appV1Api call as synchronous vs the coreV1Api call as asynchronous? OR we are just going to turn this into a Deployments example rather than a Pods example

I went sync b/c it focuses the scope of the article. Async would be a nice additional article I think so that we can go a little deeper into the motivation for that. You know I love some async.

**Pull request merged**
